### ISSUE TITLE
Count_Junction.pl is missing

### ISSUE THREAD

**Issue by msdyachkova** [kjshan/SARS-CoV-2-Mutation-Spectrum#1]
Count_Junction.pl is missing in SARS-CoV-2-Mutation-Spectrum/SARS_CoV_2_Mutation/Script/ while it is mentioned in the SARS_CoV_2_Mutation.sh. Would you be so kind as to add it? Thank you in advance.

Best, Marina.

**Comment by kjshan** [comment]
Dear Marina.

I have added this script (Count_Junction.pl) into my github folder (https://github.com/kjshan/SARS-CoV-2-Mutation-Spectrum/tree/master/SARS_CoV_2_Mutation/Script), and checked whether the other scripts exist or not.

Now, you can run the SARS_CoV_2_Mutation.sh pipeline.

Kejia

**Comment by msdyachkova** [comment]
Dear Kejia,

Thank you, everything is working now!

Best, Marina.
