### ISSUE TITLE
Mutation_Rate.pl doesn't work

### ISSUE THREAD

**Issue by msdyachkova** [kjshan/SARS-CoV-2-Mutation-Spectrum#2]
The script doesn't work. The problem is probably in lines 15-16 of Mutation_Rate.pl, where the names of the files generated as a result of the Pileup split in line 75 of the SARS_CoV_2_Mutation.sh. I'm getting names like x0000, resulting in an error. Could you please help to solve this problem?

**Comment by kjshan** [comment]
You can try the steps decribed below （all scripts have been in SARS_CoV_2_Mutation/Script） to obtain each sam or mpileup file with the same junction barcode：


cd Sam_split
perl ../Sam_split.pl ../CV_Unique.Junction.read.sam ../SCV2_Unique_UMI.txt > list.txt
parallel  -j 50 "samtools sort  {} -o ./{}.bam" :::: list.txt
parallel  -j 50 "samtools mpileup -d 0  --reference /Dell/Dell9/shankj/Cov/RTmutation/SARS-CoV-2/SARS_CoV_2/NC_045512.2.fna  --output-QNAME  --output-BP  {}.bam -o  ./{}.mpileup.default" :::: list.txt
parallel  -j 50 "perl ../Mutation_Rate.pl  {}.mpileup.default " :::: list.txt  > ../Consensus_read.out
​

**Comment by msdyachkova** [comment]
Thank you, kjshan! This code works well.
